// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.SCUP
{
    [Table("SCUP_USUARIOS")]
    public partial class ScupUsuarios
    {
        [Key]
        [Column("ID_USUARIO")]
        public int IdUsuario { get; set; }
        [Required]
        [Column("NOMBRES")]
        [StringLength(100)]
        public string Nombres { get; set; }
        [Column("APELLIDOS")]
        [StringLength(100)]
        public string Apellidos { get; set; }
        [Required]
        [Column("USERNAME")]
        [StringLength(50)]
        public string Username { get; set; }
        [Required]
        [Column("PASSWORD")]
        [MaxLength(500)]
        public byte[] Password { get; set; }
        [Column("EMAIL")]
        [StringLength(200)]
        public string Email { get; set; }
        [Column("ID_SALA")]
        public int? IdSala { get; set; }
        [Column("ID_SUCURSAL")]
        public int? IdSucursal { get; set; }
        [Column("ID_DEPARTAMENTO")]
        public int? IdDepartamento { get; set; }
        [Column("ACTIVO")]
        public bool Activo { get; set; }
        [Column("ID_TIPO_USUARIO")]
        public int IdTipoUsuario { get; set; }
        [Column("AutorizaOCE")]
        public bool? AutorizaOce { get; set; }
        [Column("RegeneraPS")]
        public bool? RegeneraPs { get; set; }
        [Column("CierraNOC")]
        public bool? CierraNoc { get; set; }
        public bool? AplicaAdmin { get; set; }
        public bool? AdjuntaArchivo { get; set; }
        public bool? AdminLarva { get; set; }
        public bool? UsaConfPer { get; set; }
        [Column("ModificaTL")]
        public bool? ModificaTl { get; set; }
        [Column("EliminaTL")]
        public bool? EliminaTl { get; set; }
    }
}