// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    /// <summary>
    /// Tabla donde se asignan los tipos de presupuesto a los centros de costo
    /// </summary>
    [Table("PR_ASIGNACION_CC_PRESUPUESTO")]
    public partial class PrAsignacionCcPresupuesto
    {
        /// <summary>
        /// Llave Primaria
        /// </summary>
        [Key]
        [Column("ID_ASIG_CC_PRESUPUESTO")]
        public int IdAsigCcPresupuesto { get; set; }
        /// <summary>
        /// llave Foranea de la Tabla Centros de Costo
        /// </summary>
        [Column("ID_CENTRO_DE_COSTO")]
        public int IdCentroDeCosto { get; set; }
        [Column("ID_TIPO_PRESUPUESTO")]
        public int IdTipoPresupuesto { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
        [StringLength(200)]
        public string NombreEquipo { get; set; }

        [ForeignKey(nameof(IdCentroDeCosto))]
        [InverseProperty(nameof(PrCentrosDeCosto.PrAsignacionCcPresupuesto))]
        public virtual PrCentrosDeCosto IdCentroDeCostoNavigation { get; set; }
        [ForeignKey(nameof(IdTipoPresupuesto))]
        [InverseProperty(nameof(PrTiposDePresupuestos.PrAsignacionCcPresupuesto))]
        public virtual PrTiposDePresupuestos IdTipoPresupuestoNavigation { get; set; }
    }
}