// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_ASIGNAR_CUENTAS_A_MATERIAL_PREVIO")]
    public partial class PrAsignarCuentasAMaterialPrevio
    {
        [Key]
        [Column("ID_ASIG_MATE_CUENTA_PREVIO")]
        public int IdAsigMateCuentaPrevio { get; set; }
        [Column("ID_MATERIAL")]
        public int? IdMaterial { get; set; }
        [Column("ID_CUENTA")]
        public int? IdCuenta { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
        [StringLength(200)]
        public string NombreEquipo { get; set; }

        [ForeignKey(nameof(IdCuenta))]
        [InverseProperty(nameof(PrCuentas.PrAsignarCuentasAMaterialPrevio))]
        public virtual PrCuentas IdCuentaNavigation { get; set; }
        [ForeignKey(nameof(IdMaterial))]
        [InverseProperty(nameof(PrMateriales.PrAsignarCuentasAMaterialPrevio))]
        public virtual PrMateriales IdMaterialNavigation { get; set; }
    }
}