// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_ASIGNAR_MATERIALES_A_CUENTA")]
    public partial class PrAsignarMaterialesACuenta
    {
        [Key]
        [Column("ID_ASIG_MATE_CUENTA")]
        public int IdAsigMateCuenta { get; set; }
        [Column("ID_CUENTA")]
        public int IdCuenta { get; set; }
        [Column("ID_MATERIAL")]
        public int IdMaterial { get; set; }
        [Column("ID_CENTRO_DE_COSTO")]
        public int IdCentroDeCosto { get; set; }
        [Column("VALOR_PROMEDIO", TypeName = "numeric(18, 2)")]
        public decimal? ValorPromedio { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
        [StringLength(200)]
        public string NombreEquipo { get; set; }

        [ForeignKey(nameof(IdCentroDeCosto))]
        [InverseProperty(nameof(PrCentrosDeCosto.PrAsignarMaterialesACuenta))]
        public virtual PrCentrosDeCosto IdCentroDeCostoNavigation { get; set; }
        [ForeignKey(nameof(IdCuenta))]
        [InverseProperty(nameof(PrCuentas.PrAsignarMaterialesACuenta))]
        public virtual PrCuentas IdCuentaNavigation { get; set; }
        [ForeignKey(nameof(IdMaterial))]
        [InverseProperty(nameof(PrMateriales.PrAsignarMaterialesACuenta))]
        public virtual PrMateriales IdMaterialNavigation { get; set; }
    }
}