// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_ASIGNAR_ESTACION_BOMBAS")]
    public partial class PrAsignarEstacionBombas
    {
        [Key]
        [Column("ID_ASIGNACION_ESTACION_BOMBAS")]
        public int IdAsignacionEstacionBombas { get; set; }
        [Column("ID_ESTACION")]
        public int IdEstacion { get; set; }
        [Column("ID_PRESUPUESTO")]
        public int IdPresupuesto { get; set; }
        [Column("ORDEN")]
        public int Orden { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }

        [ForeignKey(nameof(IdEstacion))]
        [InverseProperty(nameof(PrNumeroEstacionBombas.PrAsignarEstacionBombas))]
        public virtual PrNumeroEstacionBombas IdEstacionNavigation { get; set; }
        [ForeignKey(nameof(IdPresupuesto))]
        [InverseProperty(nameof(PrPresupuestoMaestro.PrAsignarEstacionBombas))]
        public virtual PrPresupuestoMaestro IdPresupuestoNavigation { get; set; }
    }
}