// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_ASIGNACION_CUENTAS_CC")]
    public partial class PrAsignacionCuentasCc
    {
        [Key]
        [Column("ID_ASIG_CUEN_CC")]
        public int IdAsigCuenCc { get; set; }
        [Column("ID_CUENTA")]
        public int IdCuenta { get; set; }
        [Column("ID_CENTRO_DE_COSTO")]
        public int? IdCentroDeCosto { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
        [StringLength(200)]
        public string NombreEquipo { get; set; }

        [ForeignKey(nameof(IdCentroDeCosto))]
        [InverseProperty(nameof(PrCentrosDeCosto.PrAsignacionCuentasCc))]
        public virtual PrCentrosDeCosto IdCentroDeCostoNavigation { get; set; }
        [ForeignKey(nameof(IdCuenta))]
        [InverseProperty(nameof(PrCuentas.PrAsignacionCuentasCc))]
        public virtual PrCuentas IdCuentaNavigation { get; set; }
    }
}