// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_ASIGNACION_CC_USUARIOS")]
    public partial class PrAsignacionCcUsuarios
    {
        [Key]
        [Column("ID_ASIG_CC_USUARIO")]
        public int IdAsigCcUsuario { get; set; }
        [Column("ID_CENTRO_DE_COSTO")]
        public int IdCentroDeCosto { get; set; }
        [Required]
        [Column("ID_USUARIO")]
        [StringLength(50)]
        public string IdUsuario { get; set; }
        [Column("ID_EMPRESA")]
        public int? IdEmpresa { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
        [StringLength(200)]
        public string NombreEquipo { get; set; }

        [ForeignKey(nameof(IdCentroDeCosto))]
        [InverseProperty(nameof(PrCentrosDeCosto.PrAsignacionCcUsuarios))]
        public virtual PrCentrosDeCosto IdCentroDeCostoNavigation { get; set; }
        [ForeignKey(nameof(IdEmpresa))]
        [InverseProperty(nameof(PrEmpresas.PrAsignacionCcUsuarios))]
        public virtual PrEmpresas IdEmpresaNavigation { get; set; }
    }
}