// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_ASIGNAR_MATERIALES_A_DF")]
    public partial class PrAsignarMaterialesADf
    {
        [Key]
        [Column("ID_ASIG_MAT_DF")]
        public int IdAsigMatDf { get; set; }
        [Column("ID_CONCEPTO_DF")]
        public int? IdConceptoDf { get; set; }
        [Column("ID_CUENTA")]
        public int? IdCuenta { get; set; }
        [Column("ID_MATERIAL")]
        public int? IdMaterial { get; set; }
        [Column("ID_CENTRO_DE_COSTO")]
        public int? IdCentroDeCosto { get; set; }
        [Column("ID_PRESUPUESTO")]
        public int? IdPresupuesto { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }

        [ForeignKey(nameof(IdCentroDeCosto))]
        [InverseProperty(nameof(PrCentrosDeCosto.PrAsignarMaterialesADf))]
        public virtual PrCentrosDeCosto IdCentroDeCostoNavigation { get; set; }
        [ForeignKey(nameof(IdConceptoDf))]
        [InverseProperty(nameof(PrConceptoDf.PrAsignarMaterialesADf))]
        public virtual PrConceptoDf IdConceptoDfNavigation { get; set; }
        [ForeignKey(nameof(IdCuenta))]
        [InverseProperty(nameof(PrCuentas.PrAsignarMaterialesADf))]
        public virtual PrCuentas IdCuentaNavigation { get; set; }
        [ForeignKey(nameof(IdMaterial))]
        [InverseProperty(nameof(PrMateriales.PrAsignarMaterialesADf))]
        public virtual PrMateriales IdMaterialNavigation { get; set; }
        [ForeignKey(nameof(IdPresupuesto))]
        [InverseProperty(nameof(PrPresupuestoMaestro.PrAsignarMaterialesADf))]
        public virtual PrPresupuestoMaestro IdPresupuestoNavigation { get; set; }
    }
}