// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_CATEGORIA_CUENTAS")]
    public partial class PrCategoriaCuentas
    {
        public PrCategoriaCuentas()
        {
            PrCuentas = new HashSet<PrCuentas>();
        }

        [Key]
        [Column("ID_CATEGORIA")]
        public int IdCategoria { get; set; }
        [Column("NOMBRE_CATEGORIA")]
        [StringLength(50)]
        public string NombreCategoria { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
        [StringLength(200)]
        public string NombreEquipo { get; set; }

        [InverseProperty("IdCategoriaNavigation")]
        public virtual ICollection<PrCuentas> PrCuentas { get; set; }
    }
}