// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_CENTROS_DE_COSTO")]
    public partial class PrCentrosDeCosto
    {
        public PrCentrosDeCosto()
        {
            PrAsignacionCcPresupuesto = new HashSet<PrAsignacionCcPresupuesto>();
            PrAsignacionCcUsuarios = new HashSet<PrAsignacionCcUsuarios>();
            PrAsignacionCuentasCc = new HashSet<PrAsignacionCuentasCc>();
            PrAsignarMaterialesACuenta = new HashSet<PrAsignarMaterialesACuenta>();
            PrAsignarMaterialesADf = new HashSet<PrAsignarMaterialesADf>();
            PrCcUsuarioReporte = new HashSet<PrCcUsuarioReporte>();
            PrMocAsignacionTp = new HashSet<PrMocAsignacionTp>();
            PrPresupuestoMaestro = new HashSet<PrPresupuestoMaestro>();
        }

        [Key]
        [Column("ID_CENTRO_DE_COSTO")]
        public int IdCentroDeCosto { get; set; }
        [Required]
        [Column("COD_CENTRO_DE_COSTO")]
        [StringLength(20)]
        public string CodCentroDeCosto { get; set; }
        [Required]
        [Column("NOMBRE_CENTRO_DE_COSTO")]
        [StringLength(40)]
        public string NombreCentroDeCosto { get; set; }
        [Column("ID_EMPRESA")]
        public int? IdEmpresa { get; set; }
        /// <summary>
        /// Para calcular precio unitario de jefatura gmsb
        /// </summary>
        [Column("APLICA_GMSB")]
        public bool? AplicaGmsb { get; set; }
        /// <summary>
        /// Para unir todos los centros de la finca GMSB
        /// </summary>
        [Column("ES_GMSB")]
        public bool? EsGmsb { get; set; }
        [Column("APLICA_CRIMASA")]
        public bool? AplicaCrimasa { get; set; }
        [Column("ES_CRIMASA")]
        public bool? EsCrimasa { get; set; }
        [Column("AQH_INDICADOR")]
        public bool? AqhIndicador { get; set; }
        [Column("CADELPA_INDICADOR")]
        public bool? CadelpaIndicador { get; set; }
        [Column("CRIMASA_INDICADOR")]
        public bool? CrimasaIndicador { get; set; }
        [Column("GMSB_INDICADOR")]
        public bool? GmsbIndicador { get; set; }
        [Column("SFH_INDICADOR")]
        public bool? SfhIndicador { get; set; }
        [Column("ACTIVO")]
        public bool? Activo { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
        [Column("CORREO")]
        [StringLength(50)]
        public string Correo { get; set; }
        [StringLength(100)]
        public string NombreEquipo { get; set; }
        public int? IdSectorFinca { get; set; }

        [ForeignKey(nameof(IdEmpresa))]
        [InverseProperty(nameof(PrEmpresas.PrCentrosDeCosto))]
        public virtual PrEmpresas IdEmpresaNavigation { get; set; }
        [InverseProperty("IdCentroDeCostoNavigation")]
        public virtual ICollection<PrAsignacionCcPresupuesto> PrAsignacionCcPresupuesto { get; set; }
        [InverseProperty("IdCentroDeCostoNavigation")]
        public virtual ICollection<PrAsignacionCcUsuarios> PrAsignacionCcUsuarios { get; set; }
        [InverseProperty("IdCentroDeCostoNavigation")]
        public virtual ICollection<PrAsignacionCuentasCc> PrAsignacionCuentasCc { get; set; }
        [InverseProperty("IdCentroDeCostoNavigation")]
        public virtual ICollection<PrAsignarMaterialesACuenta> PrAsignarMaterialesACuenta { get; set; }
        [InverseProperty("IdCentroDeCostoNavigation")]
        public virtual ICollection<PrAsignarMaterialesADf> PrAsignarMaterialesADf { get; set; }
        [InverseProperty("IdCentroCostoNavigation")]
        public virtual ICollection<PrCcUsuarioReporte> PrCcUsuarioReporte { get; set; }
        [InverseProperty("IdCentroDeCostoNavigation")]
        public virtual ICollection<PrMocAsignacionTp> PrMocAsignacionTp { get; set; }
        [InverseProperty("IdCentroDeCostoNavigation")]
        public virtual ICollection<PrPresupuestoMaestro> PrPresupuestoMaestro { get; set; }
    }
}