// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_CONCEPTO_DF")]
    public partial class PrConceptoDf
    {
        public PrConceptoDf()
        {
            PrAsignarMaterialesADf = new HashSet<PrAsignarMaterialesADf>();
        }

        [Key]
        [Column("ID_CONCEPTO_DF")]
        public int IdConceptoDf { get; set; }
        [Column("CONCEPTO")]
        [StringLength(100)]
        public string Concepto { get; set; }
        [Column("ID_CUENTA")]
        public int? IdCuenta { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }

        [ForeignKey(nameof(IdCuenta))]
        [InverseProperty(nameof(PrCuentas.PrConceptoDf))]
        public virtual PrCuentas IdCuentaNavigation { get; set; }
        [InverseProperty("IdConceptoDfNavigation")]
        public virtual ICollection<PrAsignarMaterialesADf> PrAsignarMaterialesADf { get; set; }
    }
}