// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_CUENTAS")]
    public partial class PrCuentas
    {
        public PrCuentas()
        {
            PrAsignacionCuentasCc = new HashSet<PrAsignacionCuentasCc>();
            PrAsignarCuentasAMaterialPrevio = new HashSet<PrAsignarCuentasAMaterialPrevio>();
            PrAsignarMaterialesACuenta = new HashSet<PrAsignarMaterialesACuenta>();
            PrAsignarMaterialesADf = new HashSet<PrAsignarMaterialesADf>();
            PrConceptoDf = new HashSet<PrConceptoDf>();
            PrPresupuestoSemanalDetalle = new HashSet<PrPresupuestoSemanalDetalle>();
        }

        [Key]
        [Column("ID_CUENTA")]
        public int IdCuenta { get; set; }
        [Required]
        [Column("COD_CUENTA")]
        [StringLength(50)]
        public string CodCuenta { get; set; }
        [Required]
        [Column("NOMBRE_CUENTA")]
        [StringLength(80)]
        public string NombreCuenta { get; set; }
        [Column("ID_CATEGORIA")]
        public int? IdCategoria { get; set; }
        [Column("EXCLUIR_CD")]
        public bool? ExcluirCd { get; set; }
        [Column("Afecta_Semanal")]
        public bool? AfectaSemanal { get; set; }
        [Column("ACTIVO")]
        public bool? Activo { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
        [Column("ID_CUENTA_DEPENDE")]
        public int? IdCuentaDepende { get; set; }
        [StringLength(200)]
        public string NombreEquipo { get; set; }

        [ForeignKey(nameof(IdCategoria))]
        [InverseProperty(nameof(PrCategoriaCuentas.PrCuentas))]
        public virtual PrCategoriaCuentas IdCategoriaNavigation { get; set; }
        [InverseProperty("IdCuentaNavigation")]
        public virtual ICollection<PrAsignacionCuentasCc> PrAsignacionCuentasCc { get; set; }
        [InverseProperty("IdCuentaNavigation")]
        public virtual ICollection<PrAsignarCuentasAMaterialPrevio> PrAsignarCuentasAMaterialPrevio { get; set; }
        [InverseProperty("IdCuentaNavigation")]
        public virtual ICollection<PrAsignarMaterialesACuenta> PrAsignarMaterialesACuenta { get; set; }
        [InverseProperty("IdCuentaNavigation")]
        public virtual ICollection<PrAsignarMaterialesADf> PrAsignarMaterialesADf { get; set; }
        [InverseProperty("IdCuentaNavigation")]
        public virtual ICollection<PrConceptoDf> PrConceptoDf { get; set; }
        [InverseProperty("IdCuentaNavigation")]
        public virtual ICollection<PrPresupuestoSemanalDetalle> PrPresupuestoSemanalDetalle { get; set; }
    }
}