// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_DATOS_FINCAS_EP_DETALLE")]
    public partial class PrDatosFincasEpDetalle
    {
        [Key]
        [Column("ID_DETALLE_DATO_EP")]
        public int IdDetalleDatoEp { get; set; }
        [Column("ID_PRESUPUESTO")]
        public int IdPresupuesto { get; set; }
        [Column("HA_SIEMBRA_DIRECTA", TypeName = "numeric(10, 2)")]
        public decimal HaSiembraDirecta { get; set; }
        [Column("HA_SIEMBRA_JUVENIL", TypeName = "numeric(10, 2)")]
        public decimal HaSiembraJuvenil { get; set; }
        [Column("HA_COSECHA", TypeName = "numeric(10, 2)")]
        public decimal HaCosecha { get; set; }
        [Column("SEMILLA_JUVENILES", TypeName = "numeric(10, 2)")]
        public decimal SemillaJuveniles { get; set; }
        [Column("SEMANAS_ATRAS_JUV_NORMALES")]
        public int SemanasAtrasJuvNormales { get; set; }
        [Column("SEMILLA_JUVENILES_MIMS", TypeName = "numeric(10, 2)")]
        public decimal SemillaJuvenilesMims { get; set; }
        [Column("SEMANAS_ATRAS_JUV_MIMS")]
        public int SemanasAtrasJuvMims { get; set; }
        [Column("LIBRAS_ENTERO_A_COSECHAR", TypeName = "numeric(10, 2)")]
        public decimal LibrasEnteroACosechar { get; set; }
        [Column("PORCENT_DE_COSECHA_PARA_ENTRO", TypeName = "numeric(10, 2)")]
        public decimal PorcentDeCosechaParaEntro { get; set; }
        [Column("PORCENTAJE_DE_FERTILIZACION", TypeName = "numeric(10, 2)")]
        public decimal PorcentajeDeFertilizacion { get; set; }
        [Column("ALIMENTO_A_UTILIZAR_SEMANA_LBS", TypeName = "numeric(10, 2)")]
        public decimal AlimentoAUtilizarSemanaLbs { get; set; }
        [Column("ALIMENTO_VIVERO_MIMS_1", TypeName = "numeric(10, 2)")]
        public decimal AlimentoViveroMims1 { get; set; }
        [Column("ALIMENTO_VIVERO_MIMS_2", TypeName = "numeric(10, 2)")]
        public decimal AlimentoViveroMims2 { get; set; }
        [Column("ALIMENTO_VIVERO_MIMS_3", TypeName = "numeric(10, 2)")]
        public decimal AlimentoViveroMims3 { get; set; }
        [Column("DISTRIBUCION_ALIMENTO_INICIADOR_1", TypeName = "numeric(10, 2)")]
        public decimal DistribucionAlimentoIniciador1 { get; set; }
        [Column("DISTRIBUCION_ALIMENTO_INICIADOR_2", TypeName = "numeric(10, 2)")]
        public decimal DistribucionAlimentoIniciador2 { get; set; }
        [Column("DISTRIBUCION_ALIMENTO_INICIADOR_3", TypeName = "numeric(10, 2)")]
        public decimal DistribucionAlimentoIniciador3 { get; set; }
        [Column("DISTRIBUCION_ALIMENTO_INICIADOR_4", TypeName = "numeric(10, 2)")]
        public decimal DistribucionAlimentoIniciador4 { get; set; }
        [Column("DISTRIBUCION_ALIMENTO_FINALIZADOR_1", TypeName = "numeric(10, 2)")]
        public decimal DistribucionAlimentoFinalizador1 { get; set; }
        [Column("DISTRIBUCION_ALIMENTO_FINALIZADOR_2", TypeName = "numeric(10, 2)")]
        public decimal DistribucionAlimentoFinalizador2 { get; set; }
        [Column("DISTRIBUCION_ALIMENTO_FINALIZADOR_3", TypeName = "numeric(10, 2)")]
        public decimal DistribucionAlimentoFinalizador3 { get; set; }
        [Column("DISTRIBUCION_ALIMENTO_FINALIZADOR_4", TypeName = "numeric(10, 2)")]
        public decimal DistribucionAlimentoFinalizador4 { get; set; }
        [Column("PORCENT_GRAIN_PELLET_MANTENIMIENTO", TypeName = "numeric(10, 2)")]
        public decimal PorcentGrainPelletMantenimiento { get; set; }
        [Column("ID_SEMANA")]
        public int IdSemana { get; set; }
        [Column("ID_TIPO_FINCA")]
        public int? IdTipoFinca { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }

        [ForeignKey(nameof(IdPresupuesto))]
        [InverseProperty(nameof(PrPresupuestoMaestro.PrDatosFincasEpDetalle))]
        public virtual PrPresupuestoMaestro IdPresupuestoNavigation { get; set; }
        [ForeignKey(nameof(IdSemana))]
        [InverseProperty(nameof(PrSemanas.PrDatosFincasEpDetalle))]
        public virtual PrSemanas IdSemanaNavigation { get; set; }
        [ForeignKey(nameof(IdTipoFinca))]
        [InverseProperty(nameof(PrTipoFinca.PrDatosFincasEpDetalle))]
        public virtual PrTipoFinca IdTipoFincaNavigation { get; set; }
    }
}