// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_EJECUCION_VS_PRESUPUESTADO")]
    public partial class PrEjecucionVsPresupuestado
    {
        [Key]
        [Column("ID_EJEC_PRESUPUESTARIA")]
        public int IdEjecPresupuestaria { get; set; }
        [Column("COD_CENTRO_DE_COSTO")]
        [StringLength(50)]
        public string CodCentroDeCosto { get; set; }
        [Column("CENTRO_DE_COSTO")]
        [StringLength(100)]
        public string CentroDeCosto { get; set; }
        [Column("COD_CUENTA")]
        [StringLength(50)]
        public string CodCuenta { get; set; }
        [Column("CUENTA")]
        [StringLength(100)]
        public string Cuenta { get; set; }
        [Column("MES")]
        public int? Mes { get; set; }
        [Column("AÑO")]
        public int? Año { get; set; }
        [Column("VALOR_MENSUAL", TypeName = "numeric(10, 2)")]
        public decimal? ValorMensual { get; set; }
        [Column("ID_CENTRO_DE_COSTO")]
        public int? IdCentroDeCosto { get; set; }
        [Column("ID_CUENTA")]
        public int? IdCuenta { get; set; }
        [Column("VALOR_PRESUPUESTADO", TypeName = "numeric(10, 2)")]
        public decimal? ValorPresupuestado { get; set; }
        [Column("JUSTIFICACION")]
        public string Justificacion { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
        [StringLength(100)]
        public string NoombreEquipo { get; set; }
        [Column("JUSTIFICACION_ACUM")]
        public string JustificacionAcum { get; set; }
    }
}