// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_EMPLEADOS")]
    public partial class PrEmpleados
    {
        public PrEmpleados()
        {
            PrFechaCanceContra = new HashSet<PrFechaCanceContra>();
            PrSueldosYSalariosDetalle = new HashSet<PrSueldosYSalariosDetalle>();
        }

        [Key]
        [Column("ID_EMPLEADO")]
        public int IdEmpleado { get; set; }
        [Column("RNP_EMPLEADO")]
        [StringLength(15)]
        public string RnpEmpleado { get; set; }
        [Column("NOMBRE_EMPLEADO")]
        [StringLength(50)]
        public string NombreEmpleado { get; set; }
        [Column("PUESTO")]
        [StringLength(100)]
        public string Puesto { get; set; }
        [Column("SUELDO_BASE", TypeName = "numeric(10, 2)")]
        public decimal? SueldoBase { get; set; }
        [Column("SUELDO_DIARIO", TypeName = "numeric(10, 6)")]
        public decimal? SueldoDiario { get; set; }
        [Column("FORMA_PAGO")]
        [StringLength(50)]
        public string FormaPago { get; set; }
        [Column("FECHA_INGRESO", TypeName = "date")]
        public DateTime? FechaIngreso { get; set; }
        [Column("GENERO")]
        [StringLength(10)]
        public string Genero { get; set; }
        [Column("ID_PRESUPUESTO")]
        public int? IdPresupuesto { get; set; }
        [Column("FECHA_CANCELACION", TypeName = "date")]
        public DateTime? FechaCancelacion { get; set; }
        [Column("CANCELACION")]
        public bool? Cancelacion { get; set; }
        [Column("ID_TIPO_CLASE")]
        public int? IdTipoClase { get; set; }
        [Column("APLICA_RECONTRATACION")]
        public bool? AplicaRecontratacion { get; set; }
        [Column("ID_PUESTO")]
        public int? IdPuesto { get; set; }
        [Column("PAGO_DINAMICO")]
        public bool? PagoDinamico { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
        [StringLength(200)]
        public string NombreEquipo { get; set; }

        [ForeignKey(nameof(IdPresupuesto))]
        [InverseProperty(nameof(PrPresupuestoMaestro.PrEmpleados))]
        public virtual PrPresupuestoMaestro IdPresupuestoNavigation { get; set; }
        [ForeignKey(nameof(IdPuesto))]
        [InverseProperty(nameof(PrPuestos.PrEmpleados))]
        public virtual PrPuestos IdPuestoNavigation { get; set; }
        [ForeignKey(nameof(IdTipoClase))]
        [InverseProperty(nameof(PrTipoDeClase.PrEmpleados))]
        public virtual PrTipoDeClase IdTipoClaseNavigation { get; set; }
        [InverseProperty("IdEmpleadoNavigation")]
        public virtual ICollection<PrFechaCanceContra> PrFechaCanceContra { get; set; }
        [InverseProperty("IdEmpleadoNavigation")]
        public virtual ICollection<PrSueldosYSalariosDetalle> PrSueldosYSalariosDetalle { get; set; }
    }
}