// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_EMPRESAS")]
    public partial class PrEmpresas
    {
        public PrEmpresas()
        {
            PrAsignacionCcUsuarios = new HashSet<PrAsignacionCcUsuarios>();
            PrCentrosDeCosto = new HashSet<PrCentrosDeCosto>();
        }

        [Key]
        [Column("ID_EMPRESA")]
        public int IdEmpresa { get; set; }
        [Required]
        [Column("COD_EMPRESA")]
        [StringLength(50)]
        public string CodEmpresa { get; set; }
        [Required]
        [Column("NOMBRE_EMPRESA")]
        [StringLength(50)]
        public string NombreEmpresa { get; set; }
        [Column("DIRECCION")]
        [StringLength(200)]
        public string Direccion { get; set; }
        [Column("ACTIVO")]
        public bool? Activo { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
        [StringLength(100)]
        public string NombreEquipo { get; set; }

        [InverseProperty("IdEmpresaNavigation")]
        public virtual ICollection<PrAsignacionCcUsuarios> PrAsignacionCcUsuarios { get; set; }
        [InverseProperty("IdEmpresaNavigation")]
        public virtual ICollection<PrCentrosDeCosto> PrCentrosDeCosto { get; set; }
    }
}