// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_GENERO")]
    public partial class PrGenero
    {
        [Key]
        [Column("ID_GENERO")]
        public int IdGenero { get; set; }
        [Required]
        [Column("NOMBRE_GENERO")]
        [StringLength(30)]
        public string NombreGenero { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
    }
}