// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_MATERIALES")]
    public partial class PrMateriales
    {
        public PrMateriales()
        {
            PrAsignarCuentasAMaterialPrevio = new HashSet<PrAsignarCuentasAMaterialPrevio>();
            PrAsignarMaterialesACuenta = new HashSet<PrAsignarMaterialesACuenta>();
            PrAsignarMaterialesADf = new HashSet<PrAsignarMaterialesADf>();
            PrPresupuestoSemanalDetalle = new HashSet<PrPresupuestoSemanalDetalle>();
        }

        [Key]
        [Column("ID_MATERIAL")]
        public int IdMaterial { get; set; }
        [Column("NOMBRE_MATERIAL")]
        [StringLength(100)]
        public string NombreMaterial { get; set; }
        [Column("ID_UNIDAD_MEDIDA")]
        public int? IdUnidadMedida { get; set; }
        [Column("PRECIO_ANTERIOR", TypeName = "numeric(10, 2)")]
        public decimal? PrecioAnterior { get; set; }
        [Column("PORCENTAJE", TypeName = "numeric(10, 2)")]
        public decimal? Porcentaje { get; set; }
        [Column("PRECIO_REAL", TypeName = "numeric(10, 2)")]
        public decimal? PrecioReal { get; set; }
        [Column("CODIGO_MATERIAL")]
        [StringLength(50)]
        public string CodigoMaterial { get; set; }
        [Column("ID_TIPO_MATERIAL")]
        public int? IdTipoMaterial { get; set; }
        [Column("AFECTA_SEMANAL")]
        public bool? AfectaSemanal { get; set; }
        [Column("ACTIVO")]
        public bool? Activo { get; set; }
        [Column("EDITABLE")]
        public bool? Editable { get; set; }
        [Column("ID_UNICO")]
        public int? IdUnico { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
        [StringLength(400)]
        public string NombreEquipo { get; set; }

        [ForeignKey(nameof(IdTipoMaterial))]
        [InverseProperty(nameof(PrTipoMaterial.PrMateriales))]
        public virtual PrTipoMaterial IdTipoMaterialNavigation { get; set; }
        [ForeignKey(nameof(IdUnidadMedida))]
        [InverseProperty(nameof(PrUnidadMedida.PrMateriales))]
        public virtual PrUnidadMedida IdUnidadMedidaNavigation { get; set; }
        [InverseProperty("IdMaterialNavigation")]
        public virtual ICollection<PrAsignarCuentasAMaterialPrevio> PrAsignarCuentasAMaterialPrevio { get; set; }
        [InverseProperty("IdMaterialNavigation")]
        public virtual ICollection<PrAsignarMaterialesACuenta> PrAsignarMaterialesACuenta { get; set; }
        [InverseProperty("IdMaterialNavigation")]
        public virtual ICollection<PrAsignarMaterialesADf> PrAsignarMaterialesADf { get; set; }
        [InverseProperty("IdMaterialNavigation")]
        public virtual ICollection<PrPresupuestoSemanalDetalle> PrPresupuestoSemanalDetalle { get; set; }
    }
}