// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_MESES")]
    public partial class PrMeses
    {
        public PrMeses()
        {
            PrMocMaestro = new HashSet<PrMocMaestro>();
            PrParameterizacionDeduccionRemuneracionId = new HashSet<PrParameterizacionDeduccionRemuneracionId>();
            PrParametrizacionMoc = new HashSet<PrParametrizacionMoc>();
            PrSemanas = new HashSet<PrSemanas>();
        }

        [Key]
        [Column("ID_MES")]
        public int IdMes { get; set; }
        [Required]
        [Column("NOMBRE_MES")]
        [StringLength(50)]
        public string NombreMes { get; set; }
        [Column("NUM_MES")]
        public int? NumMes { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
        [Column("EDITABLE")]
        public bool? Editable { get; set; }

        [InverseProperty("IdMesNavigation")]
        public virtual ICollection<PrMocMaestro> PrMocMaestro { get; set; }
        [InverseProperty("MesCalcularNavigation")]
        public virtual ICollection<PrParameterizacionDeduccionRemuneracionId> PrParameterizacionDeduccionRemuneracionId { get; set; }
        [InverseProperty("IdMesNavigation")]
        public virtual ICollection<PrParametrizacionMoc> PrParametrizacionMoc { get; set; }
        [InverseProperty("IdMesNavigation")]
        public virtual ICollection<PrSemanas> PrSemanas { get; set; }
    }
}