// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_MOC_INDICADORES")]
    public partial class PrMocIndicadores
    {
        [Key]
        [Column("ID_INDICADOR")]
        public int IdIndicador { get; set; }
        [Column("ID_CENTRO_DE_COSTO")]
        public int? IdCentroDeCosto { get; set; }
        [Column("CD_CADELPA")]
        public bool? CdCadelpa { get; set; }
        [Column("CI_CADELPA")]
        public bool? CiCadelpa { get; set; }
        [Column("CD_SAMPILE")]
        public bool? CdSampile { get; set; }
        [Column("CI_SAMPILE")]
        public bool? CiSampile { get; set; }
        [Column("CD_ESL")]
        public bool? CdEsl { get; set; }
        [Column("CI_ESL")]
        public bool? CiEsl { get; set; }
        [Column("ORDEN", TypeName = "numeric(10, 2)")]
        public decimal? Orden { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
    }
}