// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_MOC_ASIGNACION_TP_PRES")]
    public partial class PrMocAsignacionTpPres
    {
        [Key]
        [Column("ID_MOC_ASIGNACION_TP_PRES")]
        public int IdMocAsignacionTpPres { get; set; }
        [Column("ID_PRESUPUESTO")]
        public int IdPresupuesto { get; set; }
        [Column("ID_TIPO_PROCESO")]
        public int IdTipoProceso { get; set; }
        [Column("NO_USAR")]
        public bool? NoUsar { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }

        [ForeignKey(nameof(IdPresupuesto))]
        [InverseProperty(nameof(PrPresupuestoMaestro.PrMocAsignacionTpPres))]
        public virtual PrPresupuestoMaestro IdPresupuestoNavigation { get; set; }
        [ForeignKey(nameof(IdTipoProceso))]
        [InverseProperty(nameof(PrTipoProceso.PrMocAsignacionTpPres))]
        public virtual PrTipoProceso IdTipoProcesoNavigation { get; set; }
    }
}