// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_NUMERO_ESTACION_BOMBAS")]
    public partial class PrNumeroEstacionBombas
    {
        public PrNumeroEstacionBombas()
        {
            PrAsignarEstacionBombas = new HashSet<PrAsignarEstacionBombas>();
            PrDatosFincasTbDetalle = new HashSet<PrDatosFincasTbDetalle>();
        }

        [Key]
        [Column("ID_ESTACION")]
        public int IdEstacion { get; set; }
        [Required]
        [Column("ESTACION")]
        [StringLength(50)]
        public string Estacion { get; set; }
        [Column("NUM_ESTACION")]
        public int? NumEstacion { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
        [StringLength(200)]
        public string NombreEquipo { get; set; }

        [InverseProperty("IdEstacionNavigation")]
        public virtual ICollection<PrAsignarEstacionBombas> PrAsignarEstacionBombas { get; set; }
        [InverseProperty("IdEstacionNavigation")]
        public virtual ICollection<PrDatosFincasTbDetalle> PrDatosFincasTbDetalle { get; set; }
    }
}