// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_PARAME_BONIFICACIONES")]
    public partial class PrParameBonificaciones
    {
        [Key]
        [Column("ID_PARAME_BONI")]
        public int IdParameBoni { get; set; }
        [Column("AUXILIAR", TypeName = "numeric(10, 2)")]
        public decimal? Auxiliar { get; set; }
        [Column("SUPERVISOR_1", TypeName = "numeric(10, 2)")]
        public decimal? Supervisor1 { get; set; }
        [Column("SUPERVISOR_2", TypeName = "numeric(10, 2)")]
        public decimal? Supervisor2 { get; set; }
        [Column("JEFE", TypeName = "numeric(10, 2)")]
        public decimal? Jefe { get; set; }
        [Column("ID_PRESUPUESTO")]
        public int? IdPresupuesto { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }

        [ForeignKey(nameof(IdPresupuesto))]
        [InverseProperty(nameof(PrPresupuestoMaestro.PrParameBonificaciones))]
        public virtual PrPresupuestoMaestro IdPresupuestoNavigation { get; set; }
    }
}