// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_PARAMETERIZACION_DEDUCCION_REMUNERACION_ID")]
    public partial class PrParameterizacionDeduccionRemuneracionId
    {
        public PrParameterizacionDeduccionRemuneracionId()
        {
            PrSueldosYSalariosDetalle = new HashSet<PrSueldosYSalariosDetalle>();
        }

        [Key]
        [Column("ID_PARAMETRO_DR")]
        public int IdParametroDr { get; set; }
        [Required]
        [Column("NOMBRE_ID")]
        [StringLength(100)]
        public string NombreId { get; set; }
        [Column("ID_PARAMETRO")]
        public int? IdParametro { get; set; }
        [Column("APLICA_12")]
        public bool? Aplica12 { get; set; }
        [Column("MES_CALCULAR")]
        public int? MesCalcular { get; set; }
        [Column("ID_UNICO")]
        public int? IdUnico { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }

        [ForeignKey(nameof(MesCalcular))]
        [InverseProperty(nameof(PrMeses.PrParameterizacionDeduccionRemuneracionId))]
        public virtual PrMeses MesCalcularNavigation { get; set; }
        [InverseProperty("IdConceptoNavigation")]
        public virtual ICollection<PrSueldosYSalariosDetalle> PrSueldosYSalariosDetalle { get; set; }
    }
}