// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_PARAMETRIZACION_LIMITE")]
    public partial class PrParametrizacionLimite
    {
        [Key]
        [Column("ID_PARAMETRIZACION")]
        public int IdParametrizacion { get; set; }
        [Column("ID_CENTRO_DE_COSTO")]
        public int? IdCentroDeCosto { get; set; }
        [Column("LIMITE", TypeName = "numeric(14, 2)")]
        public decimal? Limite { get; set; }
        [Column("APLICA")]
        public bool? Aplica { get; set; }
        [Column("AÑO")]
        public int? Año { get; set; }
        [Column("ID_EMPRESA")]
        public int? IdEmpresa { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
        [StringLength(200)]
        public string NombreEquipo { get; set; }
    }
}