// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_PARAMETROS_SS")]
    public partial class PrParametrosSs
    {
        [Key]
        [Column("ID_PARAMETRO")]
        public int IdParametro { get; set; }
        [Column("CONCEPTO")]
        [StringLength(100)]
        public string Concepto { get; set; }
        [Column("VALOR_ACTUAL", TypeName = "numeric(12, 6)")]
        public decimal? ValorActual { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
    }
}