// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_PARAMETRIZACION_MOC")]
    public partial class PrParametrizacionMoc
    {
        [Key]
        [Column("ID_PARAMETRO_MOC")]
        public int IdParametroMoc { get; set; }
        [Column("SALARIO_MINIMO", TypeName = "numeric(10, 3)")]
        public decimal SalarioMinimo { get; set; }
        [Column("PRECIO_POR_LIBRA", TypeName = "numeric(10, 3)")]
        public decimal PrecioPorLibra { get; set; }
        [Column("BONO_EDUCATIVO", TypeName = "numeric(10, 2)")]
        public decimal? BonoEducativo { get; set; }
        [Column("ID_MES")]
        public int? IdMes { get; set; }
        [Column("ID_PRESUPUESTO")]
        public int IdPresupuesto { get; set; }
        [Column("ID_TIPO_PROCESO")]
        public int IdTipoProceso { get; set; }
        [Column("ID_TIPO_LIBRA")]
        public int? IdTipoLibra { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }

        [ForeignKey(nameof(IdMes))]
        [InverseProperty(nameof(PrMeses.PrParametrizacionMoc))]
        public virtual PrMeses IdMesNavigation { get; set; }
        [ForeignKey(nameof(IdPresupuesto))]
        [InverseProperty(nameof(PrPresupuestoMaestro.PrParametrizacionMoc))]
        public virtual PrPresupuestoMaestro IdPresupuestoNavigation { get; set; }
        [ForeignKey(nameof(IdTipoLibra))]
        [InverseProperty(nameof(PrTipoLibras.PrParametrizacionMoc))]
        public virtual PrTipoLibras IdTipoLibraNavigation { get; set; }
        [ForeignKey(nameof(IdTipoProceso))]
        [InverseProperty(nameof(PrTipoProceso.PrParametrizacionMoc))]
        public virtual PrTipoProceso IdTipoProcesoNavigation { get; set; }
    }
}