// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_PAGO_DINAMICO")]
    public partial class PrPagoDinamico
    {
        [Key]
        [Column("ID_PAGO_DINAMICO")]
        public int IdPagoDinamico { get; set; }
        [Column("ID_EMPLEADO")]
        public int? IdEmpleado { get; set; }
        [Column("SUELDO", TypeName = "numeric(10, 2)")]
        public decimal? Sueldo { get; set; }
        [Column("ID_MES")]
        public int? IdMes { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
    }
}