// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_PARAMETRIZACION_VALOR_DR")]
    public partial class PrParametrizacionValorDr
    {
        [Key]
        [Column("IDPARAMETRO")]
        public int Idparametro { get; set; }
        [Column("SEGURO_DE_VIDA", TypeName = "numeric(10, 4)")]
        public decimal? SeguroDeVida { get; set; }
        [Column("RAP_FOSOVI", TypeName = "numeric(10, 4)")]
        public decimal? RapFosovi { get; set; }
        [Column("INCREMENTO", TypeName = "numeric(10, 4)")]
        public decimal? Incremento { get; set; }
        [Column("INFOP", TypeName = "numeric(10, 4)")]
        public decimal? Infop { get; set; }
        [Column("PORCENTAJE_IHSS", TypeName = "numeric(10, 4)")]
        public decimal? PorcentajeIhss { get; set; }
        [Column("FONDO_RETIRO", TypeName = "numeric(10, 4)")]
        public decimal? FondoRetiro { get; set; }
        [Column("BONO_VACACIONAL", TypeName = "numeric(10, 4)")]
        public decimal? BonoVacacional { get; set; }
        [Column("TECHO_IHSS", TypeName = "numeric(10, 4)")]
        public decimal? TechoIhss { get; set; }
        [Column("SEGURO_ACCIDENTES", TypeName = "numeric(10, 4)")]
        public decimal? SeguroAccidentes { get; set; }
        [Column("SEGURO_MEDICO_1", TypeName = "numeric(10, 4)")]
        public decimal? SeguroMedico1 { get; set; }
        [Column("SEGURO_MEDICO_2", TypeName = "numeric(10, 4)")]
        public decimal? SeguroMedico2 { get; set; }
        [Column("INCREMENTAR_EMPLEADO", TypeName = "numeric(10, 4)")]
        public decimal? IncrementarEmpleado { get; set; }
        [Column("TECHO_BONO", TypeName = "numeric(10, 4)")]
        public decimal? TechoBono { get; set; }
        [Column("VALOR_BONO", TypeName = "numeric(10, 4)")]
        public decimal? ValorBono { get; set; }
        [Column("FONDO_AUXILIO_MUTUO", TypeName = "numeric(10, 4)")]
        public decimal? FondoAuxilioMutuo { get; set; }
        [Column("TECHO_SEGURO_MEDICO", TypeName = "numeric(20, 4)")]
        public decimal? TechoSeguroMedico { get; set; }
        [Column("PROVISION_CESANTIA_IHSS", TypeName = "numeric(20, 4)")]
        public decimal? ProvisionCesantiaIhss { get; set; }
        [Column("SEGURO_CONTRA_ACCIDENTES_IHSS", TypeName = "numeric(20, 4)")]
        public decimal? SeguroContraAccidentesIhss { get; set; }
        [Column("SEGURO_DE_VIDA_MEDICO_1", TypeName = "numeric(20, 4)")]
        public decimal? SeguroDeVidaMedico1 { get; set; }
        [Column("SEGURO_DE_VIDA_MEDICO_2", TypeName = "numeric(20, 4)")]
        public decimal? SeguroDeVidaMedico2 { get; set; }
        [Column("TECHO_RAP", TypeName = "numeric(20, 4)")]
        public decimal? TechoRap { get; set; }
        [Column("ID_PRESUPUESTO")]
        public int? IdPresupuesto { get; set; }
        [Column("TECHO_COBERTURA_RAP", TypeName = "numeric(20, 4)")]
        public decimal? TechoCoberturaRap { get; set; }
        [Column("FECHA_14AVO", TypeName = "date")]
        public DateTime? Fecha14avo { get; set; }
        [Column("FECHA_AGUINALDO", TypeName = "date")]
        public DateTime? FechaAguinaldo { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
        [StringLength(200)]
        public string NombreEquipo { get; set; }
        [Column("FECHA_AGUINALDO_II", TypeName = "date")]
        public DateTime? FechaAguinaldoIi { get; set; }
        [Column("FECHA_14AVO_II", TypeName = "date")]
        public DateTime? Fecha14avoIi { get; set; }

        [ForeignKey(nameof(IdPresupuesto))]
        [InverseProperty(nameof(PrPresupuestoMaestro.PrParametrizacionValorDr))]
        public virtual PrPresupuestoMaestro IdPresupuestoNavigation { get; set; }
    }
}