// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_SS_PRESTACIONES_DETALLE")]
    public partial class PrSsPrestacionesDetalle
    {
        [Key]
        [Column("ID_PRESTACION_DETALLE")]
        public int IdPrestacionDetalle { get; set; }
        [Column("RNP_EMPLEADO")]
        [StringLength(15)]
        public string RnpEmpleado { get; set; }
        [Column("MES_INGRESO")]
        public int? MesIngreso { get; set; }
        [Column("DIA_INGRESO")]
        public int? DiaIngreso { get; set; }
        [Column("MES_RETIRO")]
        public int? MesRetiro { get; set; }
        [Column("DIA_RETIRO")]
        public int? DiaRetiro { get; set; }
        [Column("AÑOS_SERVICIO")]
        public int? AñosServicio { get; set; }
        [Column("MESES_SERVICIO")]
        public int? MesesServicio { get; set; }
        [Column("DIAS_SERVICIO")]
        public int? DiasServicio { get; set; }
        [Column("TOTAL_DIAS")]
        public int? TotalDias { get; set; }
        [Column("SUELDO_DIARIO", TypeName = "numeric(10, 2)")]
        public decimal? SueldoDiario { get; set; }
        [Column("CALCULAR_PREAVISO")]
        public bool? CalcularPreaviso { get; set; }
        [Column("PREAVISO", TypeName = "numeric(10, 2)")]
        public decimal? Preaviso { get; set; }
        [Column("CESANTIA", TypeName = "numeric(10, 2)")]
        public decimal? Cesantia { get; set; }
        [Column("PROPORCIONAL_CESANTIA", TypeName = "numeric(10, 2)")]
        public decimal? ProporcionalCesantia { get; set; }
        [Column("PROPORCIONAL_AGUINALDO", TypeName = "numeric(10, 2)")]
        public decimal? ProporcionalAguinaldo { get; set; }
        [Column("VACACIONES_PROPORCIONAL", TypeName = "numeric(10, 2)")]
        public decimal? VacacionesProporcional { get; set; }
        [Column("PROPORCIONAL_14AVO", TypeName = "numeric(10, 2)")]
        public decimal? Proporcional14avo { get; set; }
        [Column("CALCULAR_CESANTIA")]
        public bool? CalcularCesantia { get; set; }
        [Column("CALCULAR_CESA_PROPO")]
        public bool? CalcularCesaPropo { get; set; }
        [Column("CALCULAR_VACACIONES_PROPO")]
        public bool? CalcularVacacionesPropo { get; set; }
        [Column("CALCULAR_DECIMO_CUARTO")]
        public bool? CalcularDecimoCuarto { get; set; }
        [Column("CALCULAR_DECIMO_TERCER")]
        public bool? CalcularDecimoTercer { get; set; }
        [Column("TOTAL_PRESTACIONES", TypeName = "numeric(10, 2)")]
        public decimal? TotalPrestaciones { get; set; }
        [Column("ID_PRESTACION")]
        public int? IdPrestacion { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }

        [ForeignKey(nameof(IdPrestacion))]
        [InverseProperty(nameof(PrSsPrestaciones.PrSsPrestacionesDetalle))]
        public virtual PrSsPrestaciones IdPrestacionNavigation { get; set; }
    }
}