// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_TIPO_DE_CLASE")]
    public partial class PrTipoDeClase
    {
        public PrTipoDeClase()
        {
            PrEmpleados = new HashSet<PrEmpleados>();
        }

        [Key]
        [Column("ID_TIPO_CLASE")]
        public int IdTipoClase { get; set; }
        [Column("TIPO_CLASE")]
        [StringLength(50)]
        public string TipoClase { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }

        [InverseProperty("IdTipoClaseNavigation")]
        public virtual ICollection<PrEmpleados> PrEmpleados { get; set; }
    }
}