// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_TIPO_LIBRAS")]
    public partial class PrTipoLibras
    {
        public PrTipoLibras()
        {
            PrParametrizacionMoc = new HashSet<PrParametrizacionMoc>();
        }

        [Key]
        [Column("ID_TIPO_LIBRA")]
        public int IdTipoLibra { get; set; }
        [Required]
        [Column("TIPO_LIBRA")]
        [StringLength(100)]
        public string TipoLibra { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }

        [InverseProperty("IdTipoLibraNavigation")]
        public virtual ICollection<PrParametrizacionMoc> PrParametrizacionMoc { get; set; }
    }
}