// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_TIPOS_DE_PRESUPUESTOS")]
    public partial class PrTiposDePresupuestos
    {
        public PrTiposDePresupuestos()
        {
            PrAsignacionCcPresupuesto = new HashSet<PrAsignacionCcPresupuesto>();
        }

        [Key]
        [Column("ID_TIPO_PRESUPUESTO")]
        public int IdTipoPresupuesto { get; set; }
        [Required]
        [Column("TIPO_DE_PRESUPUESTO")]
        [StringLength(100)]
        public string TipoDePresupuesto { get; set; }
        [Column("CODIGO")]
        [StringLength(10)]
        public string Codigo { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }

        [InverseProperty("IdTipoPresupuestoNavigation")]
        public virtual ICollection<PrAsignacionCcPresupuesto> PrAsignacionCcPresupuesto { get; set; }
    }
}