// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_TIPO_FINCA")]
    public partial class PrTipoFinca
    {
        public PrTipoFinca()
        {
            PrDatosFincasEpDetalle = new HashSet<PrDatosFincasEpDetalle>();
            PrRelaciones = new HashSet<PrRelaciones>();
        }

        [Key]
        [Column("ID_TIPO_FINCA")]
        public int IdTipoFinca { get; set; }
        [Required]
        [Column("TIPO_FINCA")]
        [StringLength(50)]
        public string TipoFinca { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }

        [InverseProperty("IdTipoFincaNavigation")]
        public virtual ICollection<PrDatosFincasEpDetalle> PrDatosFincasEpDetalle { get; set; }
        [InverseProperty("IdTipoFincaNavigation")]
        public virtual ICollection<PrRelaciones> PrRelaciones { get; set; }
    }
}