// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_TIPO_USUARIO")]
    public partial class PrTipoUsuario
    {
        [Key]
        [Column("ID_TIPO_USUARIO")]
        public int IdTipoUsuario { get; set; }
        [Required]
        [Column("NOMBRE_TIPO_USUARIO")]
        [StringLength(50)]
        public string NombreTipoUsuario { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
    }
}