// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_TIPO_PROCESO")]
    public partial class PrTipoProceso
    {
        public PrTipoProceso()
        {
            PrMocAsignacionTp = new HashSet<PrMocAsignacionTp>();
            PrMocAsignacionTpPres = new HashSet<PrMocAsignacionTpPres>();
            PrMocMaestro = new HashSet<PrMocMaestro>();
            PrParametrizacionMoc = new HashSet<PrParametrizacionMoc>();
        }

        [Key]
        [Column("ID_TIPO_PROCESO")]
        public int IdTipoProceso { get; set; }
        [Required]
        [Column("TIPO_PROCESO")]
        [StringLength(50)]
        public string TipoProceso { get; set; }
        [Column("NUM_PROCESO")]
        public int NumProceso { get; set; }
        [Column("ID_TP_CATEGORIA")]
        public int IdTpCategoria { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }

        [ForeignKey(nameof(IdTpCategoria))]
        [InverseProperty(nameof(PrTipoProcesoCategoria.PrTipoProceso))]
        public virtual PrTipoProcesoCategoria IdTpCategoriaNavigation { get; set; }
        [InverseProperty("IdTipoProcesoNavigation")]
        public virtual ICollection<PrMocAsignacionTp> PrMocAsignacionTp { get; set; }
        [InverseProperty("IdTipoProcesoNavigation")]
        public virtual ICollection<PrMocAsignacionTpPres> PrMocAsignacionTpPres { get; set; }
        [InverseProperty("IdTipoProcesoNavigation")]
        public virtual ICollection<PrMocMaestro> PrMocMaestro { get; set; }
        [InverseProperty("IdTipoProcesoNavigation")]
        public virtual ICollection<PrParametrizacionMoc> PrParametrizacionMoc { get; set; }
    }
}