// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_TIPO_MATERIAL")]
    public partial class PrTipoMaterial
    {
        public PrTipoMaterial()
        {
            PrMateriales = new HashSet<PrMateriales>();
        }

        [Key]
        [Column("ID_TIPO_MATERIAL")]
        public int IdTipoMaterial { get; set; }
        [Column("TIPO_MATERIAL")]
        [StringLength(20)]
        public string TipoMaterial { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }

        [InverseProperty("IdTipoMaterialNavigation")]
        public virtual ICollection<PrMateriales> PrMateriales { get; set; }
    }
}