// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_TIPO_VALOR")]
    public partial class PrTipoValor
    {
        [Key]
        [Column("ID_TIPO_VALOR")]
        public int IdTipoValor { get; set; }
        [Required]
        [Column("NOMBRE_VALOR")]
        [StringLength(50)]
        public string NombreValor { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
    }
}