// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_UNIDAD_MEDIDA")]
    public partial class PrUnidadMedida
    {
        public PrUnidadMedida()
        {
            PrMateriales = new HashSet<PrMateriales>();
        }

        [Key]
        [Column("ID_UNIDAD_MEDIDA")]
        public int IdUnidadMedida { get; set; }
        [Required]
        [Column("NOMBRE_UNIDAD_MEDIDA")]
        [StringLength(50)]
        public string NombreUnidadMedida { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
        [StringLength(200)]
        public string NombreEquipo { get; set; }

        [InverseProperty("IdUnidadMedidaNavigation")]
        public virtual ICollection<PrMateriales> PrMateriales { get; set; }
    }
}