// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_USUARIOS")]
    public partial class PrUsuarios
    {
        [Key]
        [Column("ID_USUARIO")]
        public int IdUsuario { get; set; }
        [Required]
        [Column("COD_USUARIO")]
        [StringLength(50)]
        public string CodUsuario { get; set; }
        [Required]
        [Column("NOMBRE_COMPLETO")]
        [StringLength(100)]
        public string NombreCompleto { get; set; }
        [Required]
        [Column("NOMBRE_USUARIO")]
        [StringLength(50)]
        public string NombreUsuario { get; set; }
        [Required]
        [Column("CONTRASEÑA_USUARIO")]
        [StringLength(50)]
        public string ContraseñaUsuario { get; set; }
        [Column("ID_TIPO_USUARIO")]
        public int IdTipoUsuario { get; set; }
        [Required]
        [Column("EMAIL_USUARIO")]
        [StringLength(80)]
        public string EmailUsuario { get; set; }
        [Column("ID_GENERO")]
        public int IdGenero { get; set; }
        [Column("ACTIVO")]
        public bool? Activo { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }
    }
}