// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    [Table("PR_VALOR_BONIFICACIONES")]
    public partial class PrValorBonificaciones
    {
        [Key]
        [Column("ID_VALOR_BONIFICACION")]
        public int IdValorBonificacion { get; set; }
        [Column("ENERO", TypeName = "numeric(10, 2)")]
        public decimal? Enero { get; set; }
        [Column("FEBRERO", TypeName = "numeric(10, 2)")]
        public decimal? Febrero { get; set; }
        [Column("MARZO", TypeName = "numeric(10, 2)")]
        public decimal? Marzo { get; set; }
        [Column("ABRIL", TypeName = "numeric(10, 2)")]
        public decimal? Abril { get; set; }
        [Column("MAYO", TypeName = "numeric(10, 2)")]
        public decimal? Mayo { get; set; }
        [Column("JUNIO", TypeName = "numeric(10, 2)")]
        public decimal? Junio { get; set; }
        [Column("JULIO", TypeName = "numeric(10, 2)")]
        public decimal? Julio { get; set; }
        [Column("AGOSTO", TypeName = "numeric(10, 2)")]
        public decimal? Agosto { get; set; }
        [Column("SEPTIEMBRE", TypeName = "numeric(10, 2)")]
        public decimal? Septiembre { get; set; }
        [Column("OCTUBRE", TypeName = "numeric(10, 2)")]
        public decimal? Octubre { get; set; }
        [Column("NOVIEMBRE", TypeName = "numeric(10, 2)")]
        public decimal? Noviembre { get; set; }
        [Column("DICIEMBRE", TypeName = "numeric(10, 2)")]
        public decimal? Diciembre { get; set; }
        [Column("ID_PRESUPUESTO")]
        public int? IdPresupuesto { get; set; }
        [Column("ENERO+", TypeName = "numeric(10, 2)")]
        public decimal? Enero1 { get; set; }
        [Column("FEBRERO+", TypeName = "numeric(10, 2)")]
        public decimal? Febrero1 { get; set; }
        [Column("MARZO+", TypeName = "numeric(10, 2)")]
        public decimal? Marzo1 { get; set; }
        [Column("ABRIL+", TypeName = "numeric(10, 2)")]
        public decimal? Abril1 { get; set; }
        [Column("MAYO+", TypeName = "numeric(10, 2)")]
        public decimal? Mayo1 { get; set; }
        [Column("JUNIO+", TypeName = "numeric(10, 2)")]
        public decimal? Junio1 { get; set; }
        [Column("JULIO+", TypeName = "numeric(10, 2)")]
        public decimal? Julio1 { get; set; }
        [Column("AGOSTO+", TypeName = "numeric(10, 2)")]
        public decimal? Agosto1 { get; set; }
        [Column("SEPTIEMBRE+", TypeName = "numeric(10, 2)")]
        public decimal? Septiembre1 { get; set; }
        [Column("OCTUBRE+", TypeName = "numeric(10, 2)")]
        public decimal? Octubre1 { get; set; }
        [Column("NOVIEMBRE+", TypeName = "numeric(10, 2)")]
        public decimal? Noviembre1 { get; set; }
        [Column("DICIEMBRE+", TypeName = "numeric(10, 2)")]
        public decimal? Diciembre1 { get; set; }
        [StringLength(30)]
        public string Usuario { get; set; }

        [ForeignKey(nameof(IdPresupuesto))]
        [InverseProperty(nameof(PrPresupuestoMaestro.PrValorBonificaciones))]
        public virtual PrPresupuestoMaestro IdPresupuestoNavigation { get; set; }
    }
}