// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CAEP.Data.CAEP
{
    public partial class PrVCentrosDeCosto
    {
        [Column("ID_CENTRO_DE_COSTO")]
        public int IdCentroDeCosto { get; set; }
        [Required]
        [Column("COD_CENTRO_DE_COSTO")]
        [StringLength(20)]
        public string CodCentroDeCosto { get; set; }
        [Required]
        [Column("NOMBRE_CENTRO_DE_COSTO")]
        [StringLength(40)]
        public string NombreCentroDeCosto { get; set; }
        [Column("ID_EMPRESA")]
        public int? IdEmpresa { get; set; }
        [Required]
        [Column("ID_USUARIO")]
        [StringLength(50)]
        public string IdUsuario { get; set; }
        [Column("CENTRO_DE_COSTO")]
        [StringLength(45)]
        public string CentroDeCosto { get; set; }
        [Required]
        [Column("EMPRESA")]
        [StringLength(50)]
        public string Empresa { get; set; }
    }
}